name: Rust Lint

on:
    push:
        branches: [main]
        paths:
            - "rust-zipper/**"
            - ".github/workflows/rust-lint.yml"
    pull_request:
        branches: [main]
        paths:
            - "rust-zipper/**"
            - ".github/workflows/rust-lint.yml"

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./rust-zipper

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt

            - name: Check formatting
              run: cargo fmt -- --check

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./rust-zipper

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: wasm32-unknown-unknown
                  components: clippy

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2
              with:
                  prefix-key: "rust-zipper-clippy"
                  working-directory: ./rust-zipper

            - name: Run clippy
              run: cargo clippy -- -D warnings
